### ISSUE TITLE
Connect cluster url in target namespace

### ISSUE THREAD

**Issue by murthy95** [rmarting/strimzi-migration-demo#2]
In mm2 yaml file you have mentioned the target cluster connect config as target kafka cluster bootstrap server
```
spec:
  version: 2.8.0
  replicas: 1
  # The cluster alias for Kafka Connect
  connectCluster: "my-target-cluster"
  clusters:
```
```
 - alias: "my-target-cluster"
    bootstrapServers: event-bus-kafka-bootstrap.strimzi-migration.svc:9092
    authentication: 
      type: scram-sha-512
      username: admin-user-scram
      passwordSecret:
        secretName: admin-user-scram
        password: password      
    config:
```
My question is connect cluster alias should point to a Kafka Connect cluster right since mm2 is abstracted on kafka connect. 

I am unable to understand how kafkaconnect should be specified here.
